# docker-compose.yml, builds all containers in repo to local docker library
# date: 2021-04-04
version: '3'

services:
  addsvc:
    build: './addService'
    image: local/multiservice_addsvc:latest
    ports:
      - "18081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  minussvc:
    build: './minusService'
    image: local/multiservice_minussvc:latest
    ports:
      - "18082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  multiplysvc:
    build: './multiplyService'
    image: local/multiservice_multiplysvc:latest
    ports:
      - "18083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  addAndDblsvc:
    build: './multiplyService'
    image: local/multiservice_addanddblsvc:latest
    ports:
      - "18083:8080"
  frontend:
    build: './frontEnd'
    image: local/multiservice_frontend:latest
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development