# docker-compose-from-lib.yml, pulls images from docker private repo instead of building them
# date: 2022-02-06
version: '3'

services:
  addsvc:
    image: daed.duckdns.org:50000/multiservice_addsvc:halloumi-dev
    ports:
      - "18081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
  minussvc:
    image: daed.duckdns.org:50000/multiservice_minussvc:halloumi-dev
    ports:
      - "18082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  multiplysvc:
    image: daed.duckdns.org:50000/multiservice_multiplysvc:halloumi-dev
    ports:
      - "18083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    image: daed.duckdns.org:50000/multiservice_frontend:halloumi-dev
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  addAndDblsvc:
    build: './addAndDblService'
    image: daed.duckdns.org:50000/multiservice_addanddblsvc:halloumi-dev
    ports:
      - "18084:80"