version: '3'

services:
  addsvc:
    image: daed.duckdns.org:50000/multiservice_addsvc:latest
    ports:
      - "18081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
  minussvc:
    image: daed.duckdns.org:50000/multiservice_minussvc:latest
    ports:
      - "18082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  multiplysvc:
    image: daed.duckdns.org:50000/multiservice_multiplysvc:latest
    ports:
      - "18083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    image: daed.duckdns.org:50000/multiservice_frontend:gjetost-dev
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development