# docker-compose.yml, builds all containers in repo to local docker library
# date: 2021-04-04
version: '3'

services:
  addsvc:
    build: './addService'
    image: daed.duckdns.org:50000/multiservice_addsvc:${DCADDSVCVER}
    ports:
      - "18081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  minussvc:
    build: './minusService'
    image: local/multiservice_minussvc:halloumi
    ports:
      - "18082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  multiplysvc:
    build: './multiplyService'
    image: local/multiservice_multiplysvc:halloumi
    ports:
      - "18083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  addAndDblsvc:
    build: './addAndDblService'
    image: local/multiservice_addanddblsvc:halloumi
    ports:
      - "18084:80"
  frontend:
    build: './frontEnd'
    image: local/multiservice_frontend:halloumi
    ports:
      - "18080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development