apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-fe
  labels:
    app: myservice-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-fe
  template:
    metadata:
      labels:
        app: myservice-fe
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_frontend:gjetost-dev
        name: multiservice-fe
        ports:
        - containerPort: 8080
        env: 
          - name: KUBEENV
            value: "true"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-as
  labels:
    app: myservice-as
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-as
  template:
    metadata:
      labels:
        app: myservice-as
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_addsvc:gjetost-dev
        name: multiservice-as
        ports:
        - containerPort: 8081
        securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mxs
  labels:
    app: myservice-mxs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-mxs
  template:
    metadata:
      labels:
        app: myservice-mxs
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_multiplysvc:gjetost-dev
        name: multiservice-mxs
        ports:
        - containerPort: 8082
        securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mis
  labels:
    app: myservice-mis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-mis
  template:
    metadata:
      labels:
        app: myservice-mis
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_minussvc:gjetost-dev
        name: multiservice-mis
        ports:
        - containerPort: 8083
        securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-fe
  name: myservice-fe
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myservice-fe
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-as
  name: myservice-as
spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector: 
      app: myservice-as
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: myservice-mxs
    name: myservice-mxs
  spec:
      ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
      selector: 
        app: myservice-mxs
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: myservice-mis
    name: myservice-mis
  spec:
      ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
      selector: 
        app: myservice-mis