apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-fe
  labels:
    app: myservice-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-fe
  template:
    metadata:
      labels:
        app: myservice-fe
    spec:
      hostname: multiservice-fe1
      containers:
      - image: daed.duckdns.org:50000/multiservice_frontend:latest
        name: multiservice-fe
        ports:
        - containerPort: 80
        env: 
          - name: KUBEENV
            value: "true"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-as
  labels:
    app: myservice-as
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-as
  template:
    metadata:
      labels:
        app: myservice-as
    spec:
      hostname: multiservice-as1
      containers:
      - image: daed.duckdns.org:50000/multiservice_addsvc:latest
        name: multiservice-as
        ports:
        - containerPort: 81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mxs
  labels:
    app: myservice-mxs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-mxs
  template:
    metadata:
      labels:
        app: myservice-mxs
    spec:
      hostname: multiservice-mxs1
      containers:
      - image: daed.duckdns.org:50000/multiservice_multiplysvc:latest
        name: multiservice-mxs
        ports:
        - containerPort: 82
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mis
  labels:
    app: myservice-mis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-mis
  template:
    metadata:
      labels:
        app: myservice-mis
    spec:
      hostname: multiservice-mis1
      containers:
      - image: daed.duckdns.org:50000/multiservice_minussvc:latest
        name: multiservice-mis
        ports:
        - containerPort: 83
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-fe
  name: myservice-fe
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice-fe
  type: NodePort