apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-fe
  labels:
    app: myservice-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-fe
  template:
    metadata:
      labels:
        app: myservice-fe
    spec:
      hostname: multiservice-fe1
      containers:
      - image: daed.duckdns.org:50000/multiservice_frontend
        name: multiservice-fe
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-as
  labels:
    app: myservice-as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-as
  template:
    metadata:
      labels:
        app: myservice-as
    spec:
      hostname: multiservice-as1
      containers:
      - image: daed.duckdns.org:50000/multiservice_addsvc
        name: multiservice-as
        ports:
        - containerPort: 81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mxs
  labels:
    app: myservice-mxs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-mxs
  template:
    metadata:
      labels:
        app: myservice-mxs
    spec:
      hostname: multiservice-mxs1
      containers:
      - image: daed.duckdns.org:50000/multiservice_multiplysvc
        name: multiservice-mxs
        ports:
        - containerPort: 82
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-mis
  labels:
    app: myservice-mis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice-mis
  template:
    metadata:
      labels:
        app: myservice-mis
    spec:
      hostname: multiservice-mis1
      containers:
      - image: daed.duckdns.org:50000/multiservice_minussvc
        name: multiservice-mis
        ports:
        - containerPort: 83
