apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-fe
  name: myservice-fe
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice-fe
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-as
  name: myservice-as
spec:
  ports:
  - nodePort: 30501
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice-as
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-mxs
  name: myservice-mxs
spec:
  ports:
  - nodePort: 30503
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice-mxs
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice-mis
  name: myservice-mis
spec:
  ports:
  - nodePort: 30502
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice-mis
  type: NodePort
