FROM tiangolo/uwsgi-nginx-flask:python3.12
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static
COPY ./requirements.txt /var/www/requirements.txt
RUN pip install --upgrade pip
RUN pip install -U flask-cors
RUN pip install -r /var/www/requirements.txt
COPY . . 
EXPOSE 80
